language: node_js
node_js:
  - "12"
before_script:
  - echo building $TRAVIS_BUILD_DIR
  - node --version && yarn --version
  - cd ..
  - rm -rf docusaurus
  - git clone --branch v2.0.0-alpha.40 --depth 1 https://github.com/facebook/docusaurus
  - cd docusaurus
  - mv $TRAVIS_BUILD_DIR wener
  - git apply wener/site/docusaurus.patch
script:
  - yarn upgrade && yarn
  # preprocess - fetch external resoruces
  - cd wener/site && yarn tsc && node src/preprocessors/processor.js && cd -
  - NODE_ENV=production yarn workspace wener-website build
  # restore
  - mv wener ..
  # - cd ${TRAVIS_BUILD_DIR}
  # customized public material
  # - rsync -avrc /docusaurus/wener/site/public /docusaurus/wener/site/build

# deploy to github pages
deploy:
  - provider: pages
    fqdn: wener.me
    repo: wenerme/wenerme.github.io
    token: $GITHUB_TOKEN
    # delete all the files created during the build, which will probably delete what you are trying to upload.
    # skip_cleanup: true
    cleanup: false
    # git push --force
    keep_history: false
    # org page
    target_branch: master
    # from ~/wenerme/wener
    local_dir: site/build
    on:
      branch: master

  # https://github.com/wenerme/wener.tech
  - provider: pages
    fqdn: www.wener.tech
    repo: wenerme/wener.tech
    token: $GITHUB_TOKEN
    # delete all the files created during the build, which will probably delete what you are trying to upload.
    # skip_cleanup: true
    cleanup: false
    # git push --force
    keep_history: false
    # org page
    target_branch: master
    # from ~/wenerme/wener
    local_dir: site/build
    on:
      branch: master
